/*
 * KYC API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.api;

import com.swift.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConsumptionApi
 */
@Ignore
public class ConsumptionApiTest {

    private final ConsumptionApi api = new ConsumptionApi();

    
    /**
     * Get KYC Document by Id
     *
     * This API is a consumption query that enables you to download an evidencing document for the BIC specified.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void documentNameByBicAndFolderIdGetTest() throws ApiException {
        String BIC = null;
        String documentId = null;
        Object response = api.documentNameByBicAndFolderIdGet(BIC, documentId);

        // TODO: test validations
    }
    
    /**
     * Download KYC Counterparties Data As Zip by BIC
     *
     * This API is a consumption query that enables you to extract the KYC profile in zip data folder which includes all data points (in PDFs, json, and xml) and evidencing documents spread across the 5 folder categories of the baseline for the BIC specified. Please note this API will not include the annual report and signatory list which can be downloaded via GetKYCDocument.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void entityFoldersProfileByBicGetTest() throws ApiException {
        String BIC = null;
        String lastPublishedSince = null;
        Object response = api.entityFoldersProfileByBicGet(BIC, lastPublishedSince);

        // TODO: test validations
    }
    
}
