/*
 * KYC API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.kyc.api;

import com.swift.kyc.ApiException;
import com.swift.kyc.model.EntityList;
import com.swift.kyc.model.ListOfCounterparties;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ListRetrievalApi
 */
@Ignore
public class ListRetrievalApiTest {

    private final ListRetrievalApi api = new ListRetrievalApi();

    
    /**
     * Get My Counterparties
     *
     * This API is a list retrieval query that enables you to extract a list of all counterparties which granted access to your KYC group. Triggering this API will activate/re-activate the passive relationships.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void counterpartiesMyGetTest() throws ApiException {
        ListOfCounterparties response = api.counterpartiesMyGet();

        // TODO: test validations
    }
    
    /**
     * Get My Entities
     *
     * This API is a list retrieval query that enables you to extract a list of all entities which belong to your KYC group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void entitiesMyGetTest() throws ApiException {
        EntityList response = api.entitiesMyGet();

        // TODO: test validations
    }
    
}
